inicio

  variavel real alturaDoDegrauEmCM, alturaDesejadaEmCM, quantidadeDeDegraus
  
  escrever "Informe a altura do degrau (em centímetros): "
  ler alturaDoDegrauEmCM
 
  escrever "Informe a altura que se deseja alcançar (em centímetros): "
  ler alturaDesejadaEmCM
  
  quantidadeDeDegraus <- alturaDesejadaEmCM / alturaDoDegrauEmCM
  
  escrever "Quatidade de degraus necessários para alcançar a altura desejada: ", quantidadeDeDegraus

fim
